"""Initial migration

Revision ID: ad82fb375908
Revises: 
Create Date: 2023-08-06 14:15:16.087181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad82fb375908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('endereco_cep', sa.String(length=10), nullable=True),
    sa.Column('endereco_logradouro', sa.String(length=100), nullable=True),
    sa.Column('endereco_numero', sa.String(length=10), nullable=True),
    sa.Column('endereco_complemento', sa.String(length=50), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=50), nullable=True),
    sa.Column('endereco_cidade', sa.String(length=50), nullable=True),
    sa.Column('endereco_estado', sa.String(length=50), nullable=True),
    sa.Column('identificacao_arquivo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
